#!/usr/bin/env python3
"""Generate a Markdown report for a single YouTube video."""
import json
import os
import argparse
import subprocess
from datetime import datetime
from pathlib import Path

from _utils import find_ytdlp, get_env, DATA_DIR
OUTPUT_DIR = DATA_DIR / "output"


def get_video_info(video_id):
    """Fetch video metadata using yt-dlp."""
    cmd = [find_ytdlp(), "--dump-json", "--no-download", f"https://www.youtube.com/watch?v={video_id}"]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        return json.loads(result.stdout)
    except (subprocess.TimeoutExpired, json.JSONDecodeError, FileNotFoundError) as e:
        print(f"Error fetching video info: {e}")
        return {}


def download_thumbnail(video_id, output_path):
    """Download video thumbnail."""
    cmd = [find_ytdlp(), "--write-thumbnail", "--skip-download", "-o", str(output_path / "thumbnail"),
           f"https://www.youtube.com/watch?v={video_id}"]
    subprocess.run(cmd, capture_output=True)


def generate_markdown(video_id, info, transcript_file, screenshots=None, summary=None):
    """Generate a Markdown report for the video."""
    title = info.get("title", "Unknown")
    channel = info.get("channel", "Unknown")
    upload_date = info.get("upload_date", "")
    duration = info.get("duration_string", "")
    url = f"https://www.youtube.com/watch?v={video_id}"

    md = f"""# {title}

![Thumbnail](thumbnail.webp)

## Video Info
- Channel: {channel}
- Published: {upload_date}
- Duration: {duration}
- Link: {url}

## Summary
{summary or "[Summary to be generated by Claude from the transcript]"}

"""
    if transcript_file and Path(transcript_file).exists():
        md += "## Transcript\n\n"
        md += "```\n"
        md += Path(transcript_file).read_text()[:3000]
        md += "\n```\n\n"

    if screenshots:
        md += "## Key Screenshots\n\n"
        for i, ss in enumerate(screenshots, 1):
            md += f"![Screenshot {i}]({ss})\n\n"

    return md


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--video-id", required=True)
    parser.add_argument("--output", default=str(OUTPUT_DIR))
    parser.add_argument("--summary", help="Summary content")
    args = parser.parse_args()

    output_dir = Path(args.output) / args.video_id
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Fetching video info: {args.video_id}")
    info = get_video_info(args.video_id)

    print("Downloading thumbnail...")
    download_thumbnail(args.video_id, output_dir)

    transcript_file = DATA_DIR / f"transcript_{args.video_id}.txt"

    md = generate_markdown(args.video_id, info, transcript_file, summary=args.summary)

    report_file = output_dir / "report.md"
    report_file.write_text(md, encoding="utf-8")
    print(f"Report generated: {report_file}")


if __name__ == "__main__":
    main()
